[workspace]
resolver = "3"
members = ["crates/*"]


[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
derive_more = { version = "2.1.1", features = ["full"] }
async-snmp = "0.13.0"
async-fd-lock = "0.2.0"
chrono = "0.4.44"
clap = { version = "4.6.1", features = ["derive"] }
colored_json = "5.0.0"
futures-util = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
toml = "1.1.2"
thiserror = "2.0.18"
tracing = { version = "0.1.44", features = ["log", "attributes"] }
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json", "fmt"] }
uuid = { version = "1.23.3", features = ["v4", "serde"] }
constcat = "0.6.1"
