[package]
name = "net-monitor"
version = "0.2.0"
edition = "2024"
description = "Приложение для сбора и анализа сетевых метрик"

[dependencies]
anyhow = { workspace = true }
async-fd-lock = { workspace = true }
async-snmp = "0.12.0"
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
colored_json = { workspace = true }
csv = "1.4.0"
futures-util = { workspace = true }
ping-async = "1.0.2"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
trippy-core = "0.13.0"
uuid = { workspace = true }

# [[example]]
# name = "test_traceroute"
# path = "examples/test_traceroute.rs"
